name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: installation
      run: sudo apt install -y googletest libgtest-dev build-essential gcovr mpich
    - name: make_tests
      run: g++ -std=c++17 -pthread -I/usr/include/gtest -L/usr/lib/x86_64-linux-gnu test.cpp -o program.out -lgtest -lpthread
    - name: execute_tests
      run: ./program.out
    - name: make_mpi
      run: mpic++ ../../Squirrel2/Squirrel2.cpp -o Squirrel2.out
    - name: mpi_run
      run: mpiexec -n 200 ./Squirrel2.out
